# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title FPOP2D 
#'                                                                                                        
#' @description Detecting changepoints using the functional pruning optimal partitioning method (fpop) in linear regression y = kCoef*x + aCoef.                         
#'                                                                                                       
#' @param x.                                
#' @param y.                                
#' @param penalty is a value of penalty (a non-negative real number).                                        
#' @param type is a value defining the  type of geometry for FPOP-pruning: type=1: ("intersection" of sets), approximation - rectangle.       
#'                                                                                                          
#' @return a list of 4 elements  = (chpts, kCoef, aCoef, globalCost).                    
#'  
#' \describe{
#' \item{\code{chpts}}{is the vector of changepoints.}
#' \item{\code{kCoef}}{is the vector of k.}
#' \item{\code{aCoef}}{is the vector of a.}
#' \item{\code{globalCost}}{is a number equal to the global cost.}
#' }                                                                                                                                                                             #     
#'             
#' @examples 
lrFPOP2D <- function(x, y, penalty, type) {
    .Call(`_linregFPOPdim2_lrFPOP2D`, x, y, penalty, type)
}

