# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lrFPOP2D <- function(x, y, penalty, type) {
    .Call(`_linregFPOPdim2_lrFPOP2D`, x, y, penalty, type)
}

